name: dooit
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_clean_architecture: ^6.0.2
  provider: ^6.0.0
  cloud_firestore: ^4.0.0
  firebase_auth: ^4.0.0
  intl: ^0.20.2
  test: ^1.24.0
  flutter_local_notifications: ^17.0.0
  shared_preferences: ^2.5.3
  timezone: ^0.9.2
  table_calendar: ^3.2.0
  get_it: ^7.2.0
  firebase_core: ^2.32.0
  device_info_plus: ^9.0.2
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4 # Use the latest version, check pub.dev
  build_runner: ^2.4.6 # Use the latest version, check pub.dev
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/